In [1]:
import numpy as np
import pandas as pd

In [2]:
file_path = "Census_CMA_CAagg.csv"

# Read the CSV file with 'utf-8' encoding and handle errors with 'latin-1'
try:
    df = pd.read_csv(file_path, encoding='utf-8')
except UnicodeDecodeError:
    df = pd.read_csv(file_path, encoding='latin-1')

In [3]:
df.head(25)

,CENSUS_YEAR,DGUID,GEO_LEVEL,GEO_NAME,CHARACTERISTIC_NAME,C1_COUNT_TOTAL,C2_COUNT_MEN+,C3_COUNT_WOMEN+
0,2021,2021S0503001,Census metropolitan area,St. John's,"Population, 2021",212579.00,NaN,NaN
1,2021,2021S0503001,Census metropolitan area,St. John's,"Population, 2016",208418.00,NaN,NaN
2,2021,2021S0503001,Census metropolitan area,St. John's,"Population percentage change, 2016 to 2021",2.00,NaN,NaN
3,2021,2021S0503001,Census metropolitan area,St. John's,Total private dwellings,97429.00,NaN,NaN
4,2021,2021S0503001,Census metropolitan area,St. John's,Private dwellings occupied by usual residents,89999.00,NaN,NaN
5,2021,2021S0503001,Census metropolitan area,St. John's,Population density per square kilometre,228.20,NaN,NaN
6,2021,2021S0503001,Census metropolitan area,St. John's,Land area in square kilometres,931.56,NaN,NaN
7,2021,2021S0503001,Census metropolitan area,St. John's,Total - Age groups of the population - 100% data,212580.00,103480.0,109100.0
8,2021,2021S0503001,Census metropolitan area,St. John's,0 to 14 years,31570.00,16200.0,15370.0
9,2021,2021S0503001,Census metropolitan area,St. John's,0 to 4 years,9135.00,4715.0,4420.0
10,2021,2021S0503001,Census metropolitan area,St. John's,5 to 9 years,10775.00,5510.0,5265.0
11,2021,2021S0503001,Census metropolitan area,St. John's,10 to 14 years,11655.00,5975.0,5680.0
12,2021,2021S0503001,Census metropolitan area,St. John's,15 to 64 years,142400.00,69995.0,72405.0
13,2021,2021S0503001,Census metropolitan area,St. John's,15 to 19 years,11235.00,5780.0,5455.0
14,2021,2021S0503001,Census metropolitan area,St. John's,20 to 24 years,13645.00,7080.0,6565.0
15,2021,2021S0503001,Census metropolitan area,St. John's,25 to 29 years,13605.00,6765.0,6840.0
16,2021,2021S0503001,Census metropolitan area,St. John's,30 to 34 years,14630.00,7250.0,7380.0
17,2021,2021S0503001,Census metropolitan area,St. John's,35 to 39 years,15020.00,7400.0,7625.0
18,2021,2021S0503001,Census metropolitan area,St. John's,40 to 44 years,14735.00,7065.0,7675.0
19,2021,2021S0503001,Census metropolitan area,St. John's,45 to 49 years,14490.00,7100.0,7390.0
20,2021,2021S0503001,Census metropolitan area,St. John's,50 to 54 years,14850.00,7140.0,7710.0
21,2021,2021S0503001,Census metropolitan area,St. John's,55 to 59 years,15570.00,7400.0,8170.0
22,2021,2021S0503001,Census metropolitan area,St. John's,60 to 64 years,14610.00,7015.0,7595.0
23,2021,2021S0503001,Census metropolitan area,St. John's,65 years and over,38615.00,17280.0,21330.0
24,2021,2021S0503001,Census metropolitan area,St. John's,65 to 69 years,12870.00,6115.0,6760.0

In [4]:
df['Level'] = (df['CHARACTERISTIC_NAME'].str.len() - df['CHARACTERISTIC_NAME'].str.lstrip().str.len())/2

In [5]:
max_level = int(df['Level'].max())
max_level

8

In [6]:
level_val=df['Level'].unique()
level_val

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [7]:
level_list =[]

In [8]:
level_list = ["Lvl-" + str(i) for i in range(0, max_level + 1)]

In [9]:
level_list

['Lvl-0',
 'Lvl-1',
 'Lvl-2',
 'Lvl-3',
 'Lvl-4',
 'Lvl-5',
 'Lvl-6',
 'Lvl-7',
 'Lvl-8']

In [10]:
for column_name in level_list:
        df[column_name] = column_name

In [11]:
for column_name in level_list:
        df[column_name] = np.nan

In [12]:
df

,CENSUS_YEAR,DGUID,GEO_LEVEL,GEO_NAME,CHARACTERISTIC_NAME,C1_COUNT_TOTAL,C2_COUNT_MEN+,C3_COUNT_WOMEN+,Level,Lvl-0,Lvl-1,Lvl-2,Lvl-3,Lvl-4,Lvl-5,Lvl-6,Lvl-7,Lvl-8
0,2021,2021S0503001,Census metropolitan area,St. John's,"Population, 2021",212579.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,2021S0503001,Census metropolitan area,St. John's,"Population, 2016",208418.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,2021S0503001,Census metropolitan area,St. John's,"Population percentage change, 2016 to 2021",2.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,2021S0503001,Census metropolitan area,St. John's,Total private dwellings,97429.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,2021S0503001,Census metropolitan area,St. John's,Private dwellings occupied by usual residents,89999.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420955,2021,2021S0504995,Census agglomeration,Yellowknife,Total - Eligibility and instruction in the min...,3455.0,1750.0,1705.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
420956,2021,2021S0504995,Census agglomeration,Yellowknife,Children eligible for instruction in the min...,565.0,275.0,285.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
420957,2021,2021S0504995,Census agglomeration,Yellowknife,Eligible children who have been instructed...,395.0,195.0,195.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
420958,2021,2021S0504995,Census agglomeration,Yellowknife,Eligible children who have not been instru...,165.0,80.0,90.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
420959,2021,2021S0504995,Census agglomeration,Yellowknife,Children not eligible for instruction in the...,2895.0,1475.0,1420.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_Census_CMA = df.copy()

In [14]:

# Iterate through the DataFrame rows
for index, row in df_Census_CMA.iterrows():

    for level_column in level_list:
            if row['Level'] == int(level_column.split('-')[1]):
                characteristic_name = row['CHARACTERISTIC_NAME'].strip()
                df_Census_CMA.at[index, level_column] = characteristic_name

In [15]:
df_Census_CMA.head(50)

,CENSUS_YEAR,DGUID,GEO_LEVEL,GEO_NAME,CHARACTERISTIC_NAME,C1_COUNT_TOTAL,C2_COUNT_MEN+,C3_COUNT_WOMEN+,Level,Lvl-0,Lvl-1,Lvl-2,Lvl-3,Lvl-4,Lvl-5,Lvl-6,Lvl-7,Lvl-8
0,2021,2021S0503001,Census metropolitan area,St. John's,"Population, 2021",212579.00,NaN,NaN,0.0,"Population, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,2021S0503001,Census metropolitan area,St. John's,"Population, 2016",208418.00,NaN,NaN,0.0,"Population, 2016",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,2021S0503001,Census metropolitan area,St. John's,"Population percentage change, 2016 to 2021",2.00,NaN,NaN,0.0,"Population percentage change, 2016 to 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,2021S0503001,Census metropolitan area,St. John's,Total private dwellings,97429.00,NaN,NaN,0.0,Total private dwellings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,2021S0503001,Census metropolitan area,St. John's,Private dwellings occupied by usual residents,89999.00,NaN,NaN,0.0,Private dwellings occupied by usual residents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021,2021S0503001,Census metropolitan area,St. John's,Population density per square kilometre,228.20,NaN,NaN,0.0,Population density per square kilometre,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2021,2021S0503001,Census metropolitan area,St. John's,Land area in square kilometres,931.56,NaN,NaN,0.0,Land area in square kilometres,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021,2021S0503001,Census metropolitan area,St. John's,Total - Age groups of the population - 100% data,212580.00,103480.0,109100.0,0.0,Total - Age groups of the population - 100% data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021,2021S0503001,Census metropolitan area,St. John's,0 to 14 years,31570.00,16200.0,15370.0,1.0,NaN,0 to 14 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2021,2021S0503001,Census metropolitan area,St. John's,0 to 4 years,9135.00,4715.0,4420.0,2.0,NaN,NaN,0 to 4 years,NaN,NaN,NaN,NaN,NaN,NaN
10,2021,2021S0503001,Census metropolitan area,St. John's,5 to 9 years,10775.00,5510.0,5265.0,2.0,NaN,NaN,5 to 9 years,NaN,NaN,NaN,NaN,NaN,NaN
11,2021,2021S0503001,Census metropolitan area,St. John's,10 to 14 years,11655.00,5975.0,5680.0,2.0,NaN,NaN,10 to 14 years,NaN,NaN,NaN,NaN,NaN,NaN
12,2021,2021S0503001,Census metropolitan area,St. John's,15 to 64 years,142400.00,69995.0,72405.0,1.0,NaN,15 to 64 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2021,2021S0503001,Census metropolitan area,St. John's,15 to 19 years,11235.00,5780.0,5455.0,2.0,NaN,NaN,15 to 19 years,NaN,NaN,NaN,NaN,NaN,NaN
14,2021,2021S0503001,Census metropolitan area,St. John's,20 to 24 years,13645.00,7080.0,6565.0,2.0,NaN,NaN,20 to 24 years,NaN,NaN,NaN,NaN,NaN,NaN
15,2021,2021S0503001,Census metropolitan area,St. John's,25 to 29 years,13605.00,6765.0,6840.0,2.0,NaN,NaN,25 to 29 years,NaN,NaN,NaN,NaN,NaN,NaN
16,2021,2021S0503001,Census metropolitan area,St. John's,30 to 34 years,14630.00,7250.0,7380.0,2.0,NaN,NaN,30 to 34 years,NaN,NaN,NaN,NaN,NaN,NaN
17,2021,2021S0503001,Census metropolitan area,St. John's,35 to 39 years,15020.00,7400.0,7625.0,2.0,NaN,NaN,35 to 39 years,NaN,NaN,NaN,NaN,NaN,NaN
18,2021,2021S0503001,Census metropolitan area,St. John's,40 to 44 years,14735.00,7065.0,7675.0,2.0,NaN,NaN,40 to 44 years,NaN,NaN,NaN,NaN,NaN,NaN
19,2021,2021S0503001,Census metropolitan area,St. John's,45 to 49 years,14490.00,7100.0,7390.0,2.0,NaN,NaN,45 to 49 years,NaN,NaN,NaN,NaN,NaN,NaN
20,2021,2021S0503001,Census metropolitan area,St. John's,50 to 54 years,14850.00,7140.0,7710.0,2.0,NaN,NaN,50 to 54 years,NaN,NaN,NaN,NaN,NaN,NaN
21,2021,2021S0503001,Census metropolitan area,St. John's,55 to 59 years,15570.00,7400.0,8170.0,2.0,NaN,NaN,55 to 59 years,NaN,NaN,NaN,NaN,NaN,NaN
22,2021,2021S0503001,Census metropolitan area,St. John's,60 to 64 years,14610.00,7015.0,7595.0,2.0,NaN,NaN,60 to 64 years,NaN,NaN,NaN,NaN,NaN,NaN
23,2021,2021S0503001,Census metropolitan area,St. John's,65 years and over,38615.00,17280.0,21330.0,1.0,NaN,65 years and over,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2021,2021S0503001,Census metropolitan area,St. John's,65 to 69 years,12870.00,6115.0,6760.0,2.0,NaN,NaN,65 to 69 years,NaN,NaN,NaN,NaN,NaN,NaN
25,2021,2021S0503001,Census metropolitan area,St. John's,70 to 74 years,10645.00,4875.0,5770.0,2.0,NaN,NaN,70 to 74 years,NaN,NaN,NaN,NaN,NaN,NaN
26,2021,2021S0503001,Census metropolitan area,St. John's,75 to 79 years,7185.00,3255.0,3935.0,2.0,NaN,NaN,75 to 79 years,NaN,NaN,NaN,NaN,NaN,NaN
27,2021,2021S0503001,Census metropolitan area,St. John's,80 to 84 years,4325.00,1835.0,2490.0,2.0,NaN,NaN,80 to 84 years,NaN,NaN,NaN,NaN,NaN,NaN
28,2021,2021S0503001,Census metropolitan area,St. John's,85 years and over,3585.00,1210.0,2380.0,2.0,NaN,NaN,85 years and over,NaN,NaN,NaN,NaN,NaN,NaN
29,2021,2021S0503001,Census metropolitan area,St. John's,85 to 89 years,2280.00,875.0,1405.0,3.0,NaN,NaN,NaN,85 to 89 years,NaN,NaN,NaN,NaN,NaN
30,2021,2021S0503001,Census metropolitan area,St. John's,90 to 94 years,985.00,265.0,720.0,3.0,NaN,NaN,NaN,90 to 94 years,NaN,NaN,NaN,NaN,NaN
31,2021,2021S0503001,Census metropolitan area,St. John's,95 to 99 years,285.00,60.0,225.0,3.0,NaN,NaN,NaN,95 to 99 years,NaN,NaN,NaN,NaN,NaN
32,2021,2021S0503001,Census metropolitan area,St. John's,100 years and over,25.00,10.0,25.0,3.0,NaN,NaN,NaN,100 years and over,NaN,NaN,NaN,NaN,NaN
33,2021,2021S0503001,Census metropolitan area,St. John's,Total - Distribution (%) of the population by ...,100.00,100.0,100.0,0.0,Total - Distribution (%) of the population by ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2021,2021S0503001,Census metropolitan area,St. John's,0 to 14 years,14.90,15.7,14.1,1.0,NaN,0 to 14 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2021,2021S0503001,Census metropolitan area,St. John's,15 to 64 years,67.00,67.6,66.4,1.0,NaN,15 to 64 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2021,2021S0503001,Census metropolitan area,St. John's,65 years and over,18.20,16.7,19.6,1.0,NaN,65 years and over,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2021,2021S0503001,Census metropolitan area,St. John's,85 years and over,1.70,1.2,2.2,2.0,NaN,NaN,85 years and over,NaN,NaN,NaN,NaN,NaN,NaN
38,2021,2021S0503001,Census metropolitan area,St. John's,Average age of the population,42.10,41.0,43.1,0.0,Average age of the population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2021,2021S0503001,Census metropolitan area,St. John's,Median age of the population,42.40,40.8,43.6,0.0,Median age of the population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2021,2021S0503001,Census metropolitan area,St. John's,Total - Occupied private dwellings by structur...,90000.00,NaN,NaN,0.0,Total - Occupied private dwellings by structur...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2021,2021S0503001,Census metropolitan area,St. John's,Single-detached house,49215.00,NaN,NaN,1.0,NaN,Single-detached house,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,2021,2021S0503001,Census metropolitan area,St. John's,Semi-detached house,4210.00,NaN,NaN,1.0,NaN,Semi-detached house,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,2021,2021S0503001,Census metropolitan area,St. John's,Row house,6285.00,NaN,NaN,1.0,NaN,Row house,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2021,2021S0503001,Census metropolitan area,St. John's,Apartment or flat in a duplex,22210.00,NaN,NaN,1.0,NaN,Apartment or flat in a duplex,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,2021,2021S0503001,Census metropolitan area,St. John's,Apartment in a building that has fewer than ...,7225.00,NaN,NaN,1.0,NaN,Apartment in a building that has fewer than fi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,2021,2021S0503001,Census metropolitan area,St. John's,Apartment in a building that has five or mor...,550.00,NaN,NaN,1.0,NaN,Apartment in a building that has five or more ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,2021,2021S0503001,Census metropolitan area,St. John's,Other single-attached house,155.00,NaN,NaN,1.0,NaN,Other single-attached house,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,2021,2021S0503001,Census metropolitan area,St. John's,Movable dwelling,150.00,NaN,NaN,1.0,NaN,Movable dwelling,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,2021,2021S0503001,Census metropolitan area,St. John's,Total - Private households by household size -...,90000.00,NaN,NaN,0.0,Total - Private households by household size -...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# iterate each level column and update the NaN ones based on the hierarchy
level_val=df['Level'].unique()
for i in level_val:
    i = int(i)
    last_characteristic_name = ''
    # Iterate through the DataFrame rows
    for index, row in df_Census_CMA.iterrows():
        if pd.notna(row[level_list[i]]):
            last_characteristic_name = row['CHARACTERISTIC_NAME'].strip()
        elif row['Level'] >= i:
            # Update the 'Lvl-x' column with the last_characteristic_name until the next 0 occurs
            df_Census_CMA.at[index, level_list[i]] = last_characteristic_name

In [17]:
df_Census_CMA.head(50)

,CENSUS_YEAR,DGUID,GEO_LEVEL,GEO_NAME,CHARACTERISTIC_NAME,C1_COUNT_TOTAL,C2_COUNT_MEN+,C3_COUNT_WOMEN+,Level,Lvl-0,Lvl-1,Lvl-2,Lvl-3,Lvl-4,Lvl-5,Lvl-6,Lvl-7,Lvl-8
0,2021,2021S0503001,Census metropolitan area,St. John's,"Population, 2021",212579.00,NaN,NaN,0.0,"Population, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,2021S0503001,Census metropolitan area,St. John's,"Population, 2016",208418.00,NaN,NaN,0.0,"Population, 2016",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,2021S0503001,Census metropolitan area,St. John's,"Population percentage change, 2016 to 2021",2.00,NaN,NaN,0.0,"Population percentage change, 2016 to 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,2021S0503001,Census metropolitan area,St. John's,Total private dwellings,97429.00,NaN,NaN,0.0,Total private dwellings,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,2021S0503001,Census metropolitan area,St. John's,Private dwellings occupied by usual residents,89999.00,NaN,NaN,0.0,Private dwellings occupied by usual residents,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2021,2021S0503001,Census metropolitan area,St. John's,Population density per square kilometre,228.20,NaN,NaN,0.0,Population density per square kilometre,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2021,2021S0503001,Census metropolitan area,St. John's,Land area in square kilometres,931.56,NaN,NaN,0.0,Land area in square kilometres,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2021,2021S0503001,Census metropolitan area,St. John's,Total - Age groups of the population - 100% data,212580.00,103480.0,109100.0,0.0,Total - Age groups of the population - 100% data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2021,2021S0503001,Census metropolitan area,St. John's,0 to 14 years,31570.00,16200.0,15370.0,1.0,Total - Age groups of the population - 100% data,0 to 14 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2021,2021S0503001,Census metropolitan area,St. John's,0 to 4 years,9135.00,4715.0,4420.0,2.0,Total - Age groups of the population - 100% data,0 to 14 years,0 to 4 years,NaN,NaN,NaN,NaN,NaN,NaN
10,2021,2021S0503001,Census metropolitan area,St. John's,5 to 9 years,10775.00,5510.0,5265.0,2.0,Total - Age groups of the population - 100% data,0 to 14 years,5 to 9 years,NaN,NaN,NaN,NaN,NaN,NaN
11,2021,2021S0503001,Census metropolitan area,St. John's,10 to 14 years,11655.00,5975.0,5680.0,2.0,Total - Age groups of the population - 100% data,0 to 14 years,10 to 14 years,NaN,NaN,NaN,NaN,NaN,NaN
12,2021,2021S0503001,Census metropolitan area,St. John's,15 to 64 years,142400.00,69995.0,72405.0,1.0,Total - Age groups of the population - 100% data,15 to 64 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,2021,2021S0503001,Census metropolitan area,St. John's,15 to 19 years,11235.00,5780.0,5455.0,2.0,Total - Age groups of the population - 100% data,15 to 64 years,15 to 19 years,NaN,NaN,NaN,NaN,NaN,NaN
14,2021,2021S0503001,Census metropolitan area,St. John's,20 to 24 years,13645.00,7080.0,6565.0,2.0,Total - Age groups of the population - 100% data,15 to 64 years,20 to 24 years,NaN,NaN,NaN,NaN,NaN,NaN
15,2021,2021S0503001,Census metropolitan area,St. John's,25 to 29 years,13605.00,6765.0,6840.0,2.0,Total - Age groups of the population - 100% data,15 to 64 years,25 to 29 years,NaN,NaN,NaN,NaN,NaN,NaN
16,2021,2021S0503001,Census metropolitan area,St. John's,30 to 34 years,14630.00,7250.0,7380.0,2.0,Total - Age groups of the population - 100% data,15 to 64 years,30 to 34 years,NaN,NaN,NaN,NaN,NaN,NaN
17,2021,2021S0503001,Census metropolitan area,St. John's,35 to 39 years,15020.00,7400.0,7625.0,2.0,Total - Age groups of the population - 100% data,15 to 64 years,35 to 39 years,NaN,NaN,NaN,NaN,NaN,NaN
18,2021,2021S0503001,Census metropolitan area,St. John's,40 to 44 years,14735.00,7065.0,7675.0,2.0,Total - Age groups of the population - 100% data,15 to 64 years,40 to 44 years,NaN,NaN,NaN,NaN,NaN,NaN
19,2021,2021S0503001,Census metropolitan area,St. John's,45 to 49 years,14490.00,7100.0,7390.0,2.0,Total - Age groups of the population - 100% data,15 to 64 years,45 to 49 years,NaN,NaN,NaN,NaN,NaN,NaN
20,2021,2021S0503001,Census metropolitan area,St. John's,50 to 54 years,14850.00,7140.0,7710.0,2.0,Total - Age groups of the population - 100% data,15 to 64 years,50 to 54 years,NaN,NaN,NaN,NaN,NaN,NaN
21,2021,2021S0503001,Census metropolitan area,St. John's,55 to 59 years,15570.00,7400.0,8170.0,2.0,Total - Age groups of the population - 100% data,15 to 64 years,55 to 59 years,NaN,NaN,NaN,NaN,NaN,NaN
22,2021,2021S0503001,Census metropolitan area,St. John's,60 to 64 years,14610.00,7015.0,7595.0,2.0,Total - Age groups of the population - 100% data,15 to 64 years,60 to 64 years,NaN,NaN,NaN,NaN,NaN,NaN
23,2021,2021S0503001,Census metropolitan area,St. John's,65 years and over,38615.00,17280.0,21330.0,1.0,Total - Age groups of the population - 100% data,65 years and over,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,2021,2021S0503001,Census metropolitan area,St. John's,65 to 69 years,12870.00,6115.0,6760.0,2.0,Total - Age groups of the population - 100% data,65 years and over,65 to 69 years,NaN,NaN,NaN,NaN,NaN,NaN
25,2021,2021S0503001,Census metropolitan area,St. John's,70 to 74 years,10645.00,4875.0,5770.0,2.0,Total - Age groups of the population - 100% data,65 years and over,70 to 74 years,NaN,NaN,NaN,NaN,NaN,NaN
26,2021,2021S0503001,Census metropolitan area,St. John's,75 to 79 years,7185.00,3255.0,3935.0,2.0,Total - Age groups of the population - 100% data,65 years and over,75 to 79 years,NaN,NaN,NaN,NaN,NaN,NaN
27,2021,2021S0503001,Census metropolitan area,St. John's,80 to 84 years,4325.00,1835.0,2490.0,2.0,Total - Age groups of the population - 100% data,65 years and over,80 to 84 years,NaN,NaN,NaN,NaN,NaN,NaN
28,2021,2021S0503001,Census metropolitan area,St. John's,85 years and over,3585.00,1210.0,2380.0,2.0,Total - Age groups of the population - 100% data,65 years and over,85 years and over,NaN,NaN,NaN,NaN,NaN,NaN
29,2021,2021S0503001,Census metropolitan area,St. John's,85 to 89 years,2280.00,875.0,1405.0,3.0,Total - Age groups of the population - 100% data,65 years and over,85 years and over,85 to 89 years,NaN,NaN,NaN,NaN,NaN
30,2021,2021S0503001,Census metropolitan area,St. John's,90 to 94 years,985.00,265.0,720.0,3.0,Total - Age groups of the population - 100% data,65 years and over,85 years and over,90 to 94 years,NaN,NaN,NaN,NaN,NaN
31,2021,2021S0503001,Census metropolitan area,St. John's,95 to 99 years,285.00,60.0,225.0,3.0,Total - Age groups of the population - 100% data,65 years and over,85 years and over,95 to 99 years,NaN,NaN,NaN,NaN,NaN
32,2021,2021S0503001,Census metropolitan area,St. John's,100 years and over,25.00,10.0,25.0,3.0,Total - Age groups of the population - 100% data,65 years and over,85 years and over,100 years and over,NaN,NaN,NaN,NaN,NaN
33,2021,2021S0503001,Census metropolitan area,St. John's,Total - Distribution (%) of the population by ...,100.00,100.0,100.0,0.0,Total - Distribution (%) of the population by ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,2021,2021S0503001,Census metropolitan area,St. John's,0 to 14 years,14.90,15.7,14.1,1.0,Total - Distribution (%) of the population by ...,0 to 14 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,2021,2021S0503001,Census metropolitan area,St. John's,15 to 64 years,67.00,67.6,66.4,1.0,Total - Distribution (%) of the population by ...,15 to 64 years,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2021,2021S0503001,Census metropolitan area,St. John's,65 years and over,18.20,16.7,19.6,1.0,Total - Distribution (%) of the population by ...,65 years and over,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,2021,2021S0503001,Census metropolitan area,St. John's,85 years and over,1.70,1.2,2.2,2.0,Total - Distribution (%) of the population by ...,65 years and over,85 years and over,NaN,NaN,NaN,NaN,NaN,NaN
38,2021,2021S0503001,Census metropolitan area,St. John's,Average age of the population,42.10,41.0,43.1,0.0,Average age of the population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,2021,2021S0503001,Census metropolitan area,St. John's,Median age of the population,42.40,40.8,43.6,0.0,Median age of the population,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,2021,2021S0503001,Census metropolitan area,St. John's,Total - Occupied private dwellings by structur...,90000.00,NaN,NaN,0.0,Total - Occupied private dwellings by structur...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,2021,2021S0503001,Census metropolitan area,St. John's,Single-detached house,49215.00,NaN,NaN,1.0,Total - Occupied private dwellings by structur...,Single-detached house,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,2021,2021S0503001,Census metropolitan area,St. John's,Semi-detached house,4210.00,NaN,NaN,1.0,Total - Occupied private dwellings by structur...,Semi-detached house,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,2021,2021S0503001,Census metropolitan area,St. John's,Row house,6285.00,NaN,NaN,1.0,Total - Occupied private dwellings by structur...,Row house,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,2021,2021S0503001,Census metropolitan area,St. John's,Apartment or flat in a duplex,22210.00,NaN,NaN,1.0,Total - Occupied private dwellings by structur...,Apartment or flat in a duplex,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,2021,2021S0503001,Census metropolitan area,St. John's,Apartment in a building that has fewer than ...,7225.00,NaN,NaN,1.0,Total - Occupied private dwellings by structur...,Apartment in a building that has fewer than fi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,2021,2021S0503001,Census metropolitan area,St. John's,Apartment in a building that has five or mor...,550.00,NaN,NaN,1.0,Total - Occupied private dwellings by structur...,Apartment in a building that has five or more ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,2021,2021S0503001,Census metropolitan area,St. John's,Other single-attached house,155.00,NaN,NaN,1.0,Total - Occupied private dwellings by structur...,Other single-attached house,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,2021,2021S0503001,Census metropolitan area,St. John's,Movable dwelling,150.00,NaN,NaN,1.0,Total - Occupied private dwellings by structur...,Movable dwelling,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,2021,2021S0503001,Census metropolitan area,St. John's,Total - Private households by household size -...,90000.00,NaN,NaN,0.0,Total - Private households by household size -...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_census = df_Census_CMA.copy()
# null_values = df_census.isnull()
# null_values
df_census = df_census.fillna(0)

In [19]:
df_census['Lvl-0'].unique()

array(['Population, 2021', 'Population, 2016',
       'Population percentage change, 2016 to 2021',
       'Total private dwellings',
       'Private dwellings occupied by usual residents',
       'Population density per square kilometre',
       'Land area in square kilometres',
       'Total - Age groups of the population - 100% data',
       'Total - Distribution (%) of the population by broad age groups - 100% data',
       'Average age of the population', 'Median age of the population',
       'Total - Occupied private dwellings by structural type of dwelling - 100% data',
       'Total - Private households by household size - 100% data',
       'Number of persons in private households',
       'Average household size',
       'Total - Marital status for the total population aged 15 years and over - 100% data',
       'Total - Census families in private households by family size - 100% data',
       'Average size of census families',
       'Average number of children in census families with children',
       'Total number of census families in private households - 100% data',
       'Total - Persons in private households - 100% data',
       'Total - Household type - 100% data',
       'Total - Income statistics in 2020 for the population aged 15 years and over in private households - 100% data',
       'Total - Income statistics in 2020 for the population aged 15 years and over in private households - 25% sample data',
       'Total - Employment income statistics in 2020 for the population aged 15 years and over in private households - 25% sample data',
       'Composition of total income in 2020 of the population aged 15 years and over in private households (%) - 25% sample data',
       'Total - Total income groups in 2020 for the population aged 15 years and over in private households - 100% data',
       'Total - After-tax income groups in 2020 for the population aged 15 years and over in private households - 100% data',
       'Total - Employment income groups in 2020 for the population aged 15 years and over in private households - 100% data',
       'Total - Income statistics in 2019 for the population aged 15 years and over in private households - 100% data',
       'Total - Income statistics in 2019 for the population aged 15 years and over in private households - 25% sample data',
       'Total - Employment income statistics in 2019 for the population aged 15 years and over in private households - 25% sample data',
       'Composition of total income in 2019 of the population aged 15 years and over in private households (%) - 25% sample data',
       'Total - Income statistics for private households - 100% data',
       'Total - Income statistics for private households - 25% sample data',
       'Total - Household total income groups in 2020 for private households - 100% data',
       'Total - Household after-tax income groups in 2020 for private households - 100% data',
       'Total - Income statistics for economic families in private households - 100% data',
       'Total - Income statistics for couple-only economic families in private households - 100% data',
       'Total - Income statistics for couple-with-children economic families in private households - 100% data',
       'Total - Income statistics for one-parent economic families in private households - 100% data',
       'Total - Income statistics for persons aged 15 years and over not in economic families in private households - 100% data',
       'Total - Income statistics for economic families in private households - 25% sample data',
       'Total - Income statistics for couple-only economic families in private households - 25% sample data',
       'Total - Income statistics for couple-with-children economic families in private households - 25% sample data',
       'Total - Income statistics for one-parent economic families in private households - 25% sample data',
       'Total - Income statistics for persons aged 15 years and over not in economic families in private households - 25% sample data',
       'Total - LIM low-income status in 2020 for the population in private households - 100% data',
       'In low income based on the Low-income measure, after tax (LIM-AT)',
       'Prevalence of low income based on the Low-income measure, after tax (LIM-AT) (%)',
       'Total - LICO low-income status in 2020 for the population in private households to whom the low-income concept is applicable - 100% data',
       'In low income based on the Low-income cut-offs, after tax (LICO-AT)',
       'Prevalence of low income based on the Low-income cut-offs, after tax (LICO-AT) (%)',
       'Total - Adjusted after-tax economic family income decile group for the population in private households - 100% data',
       'Total - Inequality measures for the population in private households - 100% data',
       'Total - Knowledge of official languages for the total population excluding institutional residents - 100% data',
       'Total - First official language spoken for the total population excluding institutional residents - 100% data',
       'Total - Mother tongue for the total population excluding institutional residents - 100% data',
       'Total - All languages spoken at home for the total population excluding institutional residents - 100% data',
       'Total - Language spoken most often at home for the total population excluding institutional residents - 100% data',
       'Total - Other language(s) spoken regularly at home for the total population excluding institutional residents - 100% data',
       'Total - Knowledge of languages for the population in private households - 25% sample data',
       'Total - Indigenous identity for the population in private households - 25% sample data',
       'Total - Registered or Treaty Indian status for the population in private households - 25% sample data',
       'Total - Private households by tenure - 25% sample data',
       'Total - Occupied private dwellings by condominium status - 25% sample data',
       'Total - Occupied private dwellings by number of bedrooms - 25% sample data',
       'Total - Occupied private dwellings by number of rooms - 25% sample data',
       'Average number of rooms per dwelling',
       'Total - Private households by number of persons per room - 25% sample data',
       'Total - Private households by housing suitability - 25% sample data',
       'Total - Occupied private dwellings by period of construction - 25% sample data',
       'Total - Occupied private dwellings by dwelling condition - 25% sample data',
       'Total - Private households by number of household maintainers - 25% sample data',
       'Total - Private households by age of primary household maintainers - 25% sample data',
       'Total - Owner and tenant households with household total income greater than zero, in non-farm, non-reserve private dwellings by shelter-cost-to-income ratio - 25% sample data',
       'Total - Occupied private dwellings by housing indicators - 25% sample data',
       'Total - Owner and tenant households with household total income greater than zero and shelter-cost-to-income ratio less than 100%, in non-farm, non-reserve private dwellings - 25% sample data',
       'Total - Owner households in non-farm, non-reserve private dwellings - 25% sample data',
       'Total - Tenant households in non-farm, non-reserve private dwellings - 25% sample data',
       'Total - Households living in a dwelling provided by the local government, First Nation or Indian band in non-farm private dwellings - 25% sample data',
       'Total - Indigenous ancestry for the population in private households - 25% sample data',
       'Total - Citizenship for the population in private households - 25% sample data',
       'Total - Immigrant status and period of immigration for the population in private households - 25% sample data',
       'Total - Age at immigration for the immigrant population in private households - 25% sample data',
       'Total - Place of birth for the immigrant population in private households - 25% sample data',
       'Total - Place of birth for the recent immigrant population in private households - 25% sample data',
       'Total - Generation status for the population in private households - 25% sample data',
       'Total - Admission category and applicant type for the immigrant population in private households who were admitted between 1980 and 2021 - 25% sample data',
       'Total - Pre-admission experience for the immigrant population in private households who were admitted between 1980 and 2021 - 25% sample data',
       'Total - Visible minority for the population in private households - 25% sample data',
       'Total - Ethnic or cultural origin for the population in private households - 25% sample data',
       'Total - Religion for the population in private households - 25% sample data',
       'Total - Mobility status 1 year ago - 25% sample data',
       'Total - Mobility status 5 years ago - 25% sample data',
       'Total - Secondary (high) school diploma or equivalency certificate for the population aged 15 years and over in private households - 25% sample data',
       'Total - Secondary (high) school diploma or equivalency certificate for the population aged 25 to 64 years in private households - 25% sample data',
       'Total - Highest certificate, diploma or degree for the population aged 15 years and over in private households - 25% sample data',
       'Total - Highest certificate, diploma or degree for the population aged 25 to 64 years in private households - 25% sample data',
       'Total - Major field of study - Classification of Instructional Programs (CIP) 2021 for the population aged 15 years and over in private households - 25% sample data',
       'Total - Major field of study - Classification of Instructional Programs (CIP) 2021 for the population aged 25 to 64 years in private households - 25% sample data',
       'Total - Location of study compared with province or territory of residence for the population aged 25 to 64 years in private households - 25% sample data',
       'Total - Population aged 15 years and over by labour force status - 25% sample data',
       'Participation rate', 'Employment rate', 'Unemployment rate',
       'Total - Population aged 15 years and over by work activity during the reference year - 25% sample data',
       'Total - Labour force aged 15 years and over by class of worker including job permanency - 25% sample data',
       'Total - Labour force aged 15 years and over by occupation - Broad category - National Occupational Classification (NOC) 2021 - 25% sample data',
       'Total - Labour force aged 15 years and over by industry - Sectors - North American Industry Classification System (NAICS) 2017 - 25% sample data',
       'Total - All languages used at work for the population in private households aged 15 years and over who worked since January 1, 2020 - 25% sample data',
       'Total - Language used most often at work for the population aged 15 years and over who worked since January 1, 2020, in private households, 2021 Census - 25% sample data',
       'Total - Other language(s) used regularly at work for the population in private households aged 15 years and over who worked since January 1, 2020 - 25% sample data',
       'Total - Place of work status for the employed labour force aged 15 years and over - 25% sample data',
       'Total - Commuting destination for the employed labour force aged 15 years and over with a usual place of work - 25% sample data',
       'Total - Main mode of commuting for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data',
       'Total - Commuting duration for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data',
       'Total - Time leaving for work for the employed labour force aged 15 years and over with a usual place of work or no fixed workplace address - 25% sample data',
       'Total - Eligibility for instruction in the minority official language for the population in private households born in 2003 or later - 100% data',
       'Total - Eligibility and instruction in the minority official language, for the population in private households born between 2003 and 2015 (inclusive) - 100% data'],
      dtype=object)

In [20]:
df_census['Lvl-1'].unique()

array([0, '0 to 14 years', '15 to 64 years', '65 years and over',
       'Single-detached house', 'Semi-detached house', 'Row house',
       'Apartment or flat in a duplex',
       'Apartment in a building that has fewer than five storeys',
       'Apartment in a building that has five or more storeys',
       'Other single-attached house', 'Movable dwelling', '1 person',
       '2 persons', '3 persons', '4 persons', '5 or more persons',
       'Married or living common-law',
       'Not married and not living common-law', 'Total couple families',
       'Total one-parent families', 'Total - Persons in census families',
       'Total - Persons not in census families in private households - 100% data',
       'One-census-family households without additional persons',
       'Multigenerational households',
       'Multiple-census-family households',
       'One-census-family households with additional persons',
       'Two-or-more-person non-census-family households',
       'One-person households',
       'Number of total income recipients aged 15 years and over in private households in 2020 - 100% data',
       'Number of after-tax income recipients aged 15 years and over in private households in 2020 - 100% data',
       'Number of market income recipients aged 15 years and over in private households in 2020 - 100% data',
       'Number of employment income recipients aged 15 years and over in private households in 2020 - 100% data',
       'Number of government transfers recipients aged 15 years and over in private households in 2020 - 100% data',
       'Number of employment insurance benefits recipients aged 15 years and over in private households in 2020 - 100% data',
       'Number of COVID-19 emergency and recovery benefits recipients aged 15 years and over in private households in 2020 - 100% data',
       'Number of total income recipients aged 15 years and over in private households in 2020 - 25% sample data',
       'Number of after-tax income recipients aged 15 years and over in private households in 2020 - 25% sample data',
       'Number of market income recipients aged 15 years and over in private households in 2020 - 25% sample data',
       'Number of employment income recipients aged 15 years and over in private households in 2020 - 25% sample data',
       'Number of government transfers recipients aged 15 years and over in private households in 2020 - 25% sample data',
       'Number of employment insurance benefits recipients aged 15 years and over in private households in 2020 - 25% sample data',
       'Number of COVID-19 emergency and recovery benefits recipients aged 15 years and over in private households in 2020 - 25% sample data',
       'Number of employment income recipients in 2020 who worked full-year full-time in 2020 - 25% sample data',
       'Number of employment income recipients in 2020 who worked part-year or part-time in 2020 - 25% sample data',
       'Market income (%)', 'Government transfers (%)',
       'Without total income', 'With total income',
       'Without after-tax income', 'With after-tax income',
       'Without employment income', 'With employment income',
       'Number of total income recipients aged 15 years and over in private households in 2019 - 100% data',
       'Number of after-tax income recipients aged 15 years and over in private households in 2019 - 100% data',
       'Number of market income recipients aged 15 years and over in private households in 2019 - 100% data',
       'Number of employment income recipients aged 15 years and over in private households in 2019 - 100% data',
       'Number of government transfers recipients aged 15 years and over in private households in 2019 - 100% data',
       'Number of employment insurance benefits recipients aged 15 years and over in private households in 2019 -100% data',
       'Number of total income recipients aged 15 years and over in private households in 2019 - 25% sample data',
       'Number of after-tax income recipients aged 15 years and over in private households in 2019 - 25% sample data',
       'Number of market income recipients aged 15 years and over in private households in 2019 - 25% sample data',
       'Number of employment income recipients aged 15 years and over in private households in 2019 - 25% sample data',
       'Number of government transfers recipients aged 15 years and over in private households in 2019 - 25% sample data',
       'Number of employment insurance benefits recipients aged 15 years and over in private households in 2019 - 25% sample data',
       'Number of employment income recipients in 2019 who worked full-year full-time in 2020 - 25% sample data',
       'Number of employment income recipients in 2019 who worked part-year or part-time in 2020 - 25% sample data',
       'Median total income of household in 2020 ($)',
       'Median after-tax income of household in 2020 ($)',
       'Average total income of household in 2020 ($)',
       'Average after-tax income of household in 2020 ($)',
       'Under $5,000', '$5,000 to $9,999', '$10,000 to $14,999',
       '$15,000 to $19,999', '$20,000 to $24,999', '$25,000 to $29,999',
       '$30,000 to $34,999', '$35,000 to $39,999', '$40,000 to $44,999',
       '$45,000 to $49,999', '$50,000 to $59,999', '$60,000 to $69,999',
       '$70,000 to $79,999', '$80,000 to $89,999', '$90,000 to $99,999',
       '$100,000 and over',
       'Median total income of economic family in 2020 ($)',
       'Median after-tax income of economic family in 2020 ($)',
       'Average family size of economic families',
       'Median total income of couple-only economic families in 2020 ($)',
       'Median after-tax income of couple-only economic families in 2020 ($)',
       'Average family size of couple-only economic families',
       'Median total income of couple-with-children economic families  in 2020 ($)',
       'Median after-tax income of couple-with-children economic families in 2020 ($)',
       'Average family size of couple-with-children economic families',
       'Median total income of one-parent economic families in 2020 ($)',
       'Median after-tax income of one-parent economic families in 2020 ($)',
       'Average family size of one-parent economic families',
       'Median total income in 2020 ($)',
       'Median after-tax income in 2020 ($)',
       'Average total income of economic family in 2020 ($)',
       'Average after-tax income of economic family in 2020 ($)',
       'Average total income of couple-only economic families in 2020 ($)',
       'Average after-tax income of couple-only economic families in 2020 ($)',
       'Average total income of couple-with-children economic families in 2020 ($)',
       'Average after-tax income of couple-with-children economic families in 2020 ($)',
       'Average total income of one-parent economic families in 2020 ($)',
       'Average after-tax income of one-parent economic families in 2020 ($)',
       'Average total income in 2020 ($)',
       'Average after-tax income in 2020 ($)', '0 to 17 years',
       '18 to 64 years', '0 to 17 years (%)', '18 to 64 years (%)',
       '65 years and over (%)', 'In bottom half of the distribution',
       'In top half of the distribution',
       'Gini index on adjusted household total income',
       'Gini index on adjusted household market income',
       'Gini index on adjusted household after-tax income',
       'P90/P10 ratio on adjusted household after-tax income',
       'English only', 'French only', 'English and French',
       'Neither English nor French', 'English', 'French',
       'Single responses', 'Multiple responses', 'Non-official language',
       'English and non-official language(s)',
       'French and non-official language(s)',
       'English, French and non-official language(s)',
       'Multiple non-official languages', 'None', 'Official languages',
       'Non-official languages', 'Indigenous identity',
       'Non-Indigenous identity', 'Registered or Treaty Indian',
       'Not a Registered or Treaty Indian', 'Owner', 'Renter',
       'Dwelling provided by the local government, First Nation or Indian band',
       'Condominium', 'Not condominium', 'No bedrooms', '1 bedroom',
       '2 bedrooms', '3 bedrooms', '4 or more bedrooms', '1 to 4 rooms',
       '5 rooms', '6 rooms', '7 rooms', '8 or more rooms',
       'One person or fewer per room', 'More than one person per room',
       'Suitable', 'Not suitable', '1960 or before', '1961 to 1980',
       '1981 to 1990', '1991 to 2000', '2001 to 2005', '2006 to 2010',
       '2011 to 2015', '2016 to 2021',
       'Only regular maintenance and minor repairs needed',
       'Major repairs needed', 'One-maintainer household',
       'Two-maintainer household', 'Three-or-more-maintainer household',
       '15 to 24 years', '25 to 34 years', '35 to 44 years',
       '45 to 54 years', '55 to 64 years', '65 to 74 years',
       '75 to 84 years', '85 years and over',
       'Spending less than 30% of income on shelter costs',
       'Spending 30% or more of income on shelter costs',
       "Total - Households 'spending 30% or more of income on shelter costs' or 'not suitable' or 'major repairs needed'",
       'Acceptable housing', 'In core need', 'Not in core need',
       '% of owner households with a mortgage',
       '% of owner households spending 30% or more of its income on shelter costs',
       '% in core housing need',
       'Median monthly shelter costs for owned dwellings ($)',
       'Average monthly shelter costs for owned dwellings ($)',
       'Median value of dwellings ($)', 'Average value of dwellings ($)',
       '% of tenant households in subsidized housing',
       '% of tenant households spending 30% or more of its income on shelter costs',
       'Median monthly shelter costs for rented dwellings ($)',
       'Average monthly shelter costs for rented dwellings ($)',
       '% of households living in a dwelling provided by the local government, First Nation or Indian band spending more than 30% on shelter costs',
       'Median monthly shelter costs for dwellings provided by local government, First Nation or Indian band ($)',
       'Average monthly shelter costs for dwellings provided by local government, First Nation or Indian band ($)',
       'Indigenous ancestry (only)',
       'Indigenous and non-Indigenous ancestries',
       'Non-Indigenous ancestry only', 'Canadian citizens',
       'Not Canadian citizens', 'Non-immigrants', 'Immigrants',
       'Non-permanent residents', 'Under 5 years', '5 to 14 years',
       '25 to 44 years', '45 years and over', 'Americas', 'Europe',
       'Africa', 'Asia', 'Oceania and other places of birth',
       'Oceania and other', 'First generation', 'Second generation',
       'Third generation or more', 'Economic immigrants',
       'Immigrants sponsored by family', 'Refugees', 'Other immigrants',
       'Asylum claim before admission',
       'Work permits only before admission',
       'Study permits only before admission',
       'Work and study permits before admission',
       'Other permits before admission', 'No pre-admission experience',
       'Total visible minority population', 'Not a visible minority',
       'Canadian', 'Irish', 'Scottish', 'French, n.o.s.', 'German',
       'Chinese', 'Italian', 'Indian (India)', 'Ukrainian', 'Dutch',
       'Polish', 'Québécois', 'British Isles, n.o.s.', 'Filipino',
       'French Canadian', 'Caucasian (White), n.o.s.',
       'First Nations (North American Indian), n.o.s.', 'Métis',
       'European, n.o.s.', 'Russian', 'Norwegian', 'Welsh', 'Portuguese',
       'American', 'Spanish', 'Swedish', 'Hungarian', 'Acadian',
       'Pakistani', 'African, n.o.s.', 'Jewish', 'Punjabi', 'Vietnamese',
       'Arab, n.o.s.', 'Greek', 'Jamaican', 'Asian, n.o.s.',
       'Cree, n.o.s.', 'Korean', 'Romanian', 'Lebanese', 'Iranian',
       'Christian, n.i.e.', 'Danish', 'North American Indigenous, n.o.s.',
       'Sikh', 'Austrian', 'Belgian', 'Haitian', 'Hindu', 'Mexican',
       'Mennonite', 'Swiss', 'Finnish', 'Sri Lankan', 'Croatian',
       'Japanese', 'South Asian, n.o.s.', "Mi'kmaq, n.o.s.",
       'Northern European, n.o.s.', 'Muslim', 'Egyptian',
       'Latin, Central or South American, n.o.s.', 'Tamil', 'Icelandic',
       'Colombian', 'Moroccan', 'Czech', 'Syrian', 'Guyanese', 'Afghan',
       'Black, n.o.s.', 'Serbian', 'Ojibway', 'Newfoundlander',
       'Hong Konger', 'Ontarian', 'Persian', 'Trinidadian/Tobagonian',
       'Turkish', 'Inuit, n.o.s.', 'Bangladeshi', 'Algerian', 'Brazilian',
       'Nigerian', 'Armenian', 'Slovak', 'Eastern European, n.o.s.',
       'Somali', 'Taiwanese', 'Iraqi', 'Salvadorean', 'African Caribbean',
       'East or Southeast Asian, n.o.s.',
       'West or Central Asian or Middle Eastern, n.o.s.',
       'Caribbean, n.o.s.', 'Algonquin', 'West Indian, n.o.s.',
       'Lithuanian', 'South African', 'Australian', 'Palestinian',
       'Chilean', 'Congolese', 'Nova Scotian', 'Ethiopian',
       'Hispanic, n.o.s.', 'Peruvian', 'Yoruba', 'Cambodian (Khmer)',
       'Berber', 'Albanian', 'Maltese', 'Macedonian', 'Slovenian',
       'Western European, n.o.s.', 'New Brunswicker', 'Gujarati',
       'Eritrean', 'African Canadian', 'Israeli', 'Mohawk',
       'Czechoslovakian, n.o.s.', 'Bulgarian', 'Albertan', 'Ghanaian',
       'Barbadian', 'African American', 'Yugoslavian, n.o.s.', 'Tunisian',
       'Slavic, n.o.s.', 'Cuban', 'Bosnian', 'Venezuelan',
       'Innu/Montagnais, n.o.s.', 'Latvian', 'Bengali', 'Cameroonian',
       'Guatemalan', 'Indonesian', 'Laotian', 'Ilocano', 'Northern Irish',
       'Celtic, n.o.s.', 'British Columbian', 'Ecuadorian',
       'Franco Ontarian', 'Argentinian', 'Estonian', 'Kurdish', 'Fijian',
       'Jatt', 'North American, n.o.s.', 'Coptic', 'Thai', 'Dominican',
       'Nepali', 'Kabyle', 'Assyrian', 'Igbo', 'Byelorussian',
       'Dene, n.o.s.', 'Blackfoot, n.o.s.', 'Abenaki', 'Moldovan',
       'Iroquois (Haudenosaunee), n.o.s.', 'New Zealander', 'Sudanese',
       'Breton', 'Pennsylvania Dutch', 'Malaysian', 'Plains Cree',
       'North African, n.o.s.', 'Huron (Wendat)', 'Saskatchewanian',
       'Buddhist', 'Gaspesian', 'Norman',
       'Southern or East African, n.o.s.', 'Ivorian', 'Saulteaux',
       'Anishinaabe, n.o.s.', 'Burundian', 'Tigrinya', 'Nicaraguan',
       'Mauritian', 'Kenyan', 'Oji-Cree', 'Vincentian', 'Jordanian',
       'Manitoban', 'Cape Bretoner', 'Rwandan', 'Grenadian', 'Malayali',
       'Chaldean', 'Sinhalese', 'Mayan', 'Honduran', 'Cherokee',
       "Qalipu Mi'kmaq", 'Indo-Caribbean', 'Flemish',
       'United Empire Loyalist', 'Senegalese', 'Azerbaijani', 'Sicilian',
       'Pashtun', 'Malay', 'Goan', 'Bantu, n.o.s.', 'Tibetan',
       'Zimbabwean', 'Burmese', 'Mongolian', 'Azorean', 'Atikamekw',
       'Bamileke', 'Indo-Guyanese', 'Ugandan', 'Oromo', 'Tanzanian',
       'Yemeni', 'Central African', 'Libyan', 'Basque', 'Uruguayan',
       'Akan, n.o.s.', 'Central or West African, n.o.s.', 'Igorot',
       'Fulani', 'Woodland Cree', 'Guinean', 'St. Lucian',
       'Prince Edward Islander', 'Maliseet', 'Beninese', 'Telugu', 'Roma',
       'Costa Rican', 'African Nova Scotian', 'Malagasy', 'Kashmiri',
       'Singaporean', 'Karen', 'Edo', 'Tajik', 'Amhara', 'Paraguayan',
       'Christian',
       'Traditional (North American Indigenous) spirituality',
       'Other religions and spiritual traditions',
       'No religion and secular perspectives', 'Non-movers', 'Movers',
       'No high school diploma or equivalency certificate',
       'With high school diploma or equivalency certificate',
       'No certificate, diploma or degree',
       'High (secondary) school diploma or equivalency certificate',
       'Postsecondary certificate, diploma or degree',
       'No postsecondary certificate, diploma or degree', 'Education',
       'Visual and performing arts, and communications technologies',
       'Humanities', 'Social and behavioural sciences and law',
       'Business, management and public administration',
       'Physical and life sciences and technologies',
       'Mathematics, computer and information sciences',
       'Architecture, engineering, and related trades',
       'Agriculture, natural resources and conservation',
       'Health and related fields',
       'Personal, protective and transportation services', 'Other',
       'In the labour force', 'Not in the labour force', 'Did not work',
       'Worked', 'Class of worker - not applicable',
       'All classes of workers', 'Occupation - not applicable',
       'All occupations', 'Industry - not applicable', 'All industries',
       'Worked at home', 'Worked outside Canada',
       'No fixed workplace address', 'Usual place of work',
       'Commute within census subdivision (CSD) of residence',
       'Commute to a different census subdivision (CSD) within census division (CD) of residence',
       'Commute to a different census subdivision (CSD) and census division (CD) within province or territory of residence',
       'Commute to a different province or territory',
       'Car, truck or van', 'Public transit', 'Walked', 'Bicycle',
       'Other method', 'Less than 15 minutes', '15 to 29 minutes',
       '30 to 44 minutes', '45 to 59 minutes', '60 minutes and over',
       'Between 5 a.m. and 5:59 a.m.', 'Between 6 a.m. and 6:59 a.m.',
       'Between 7 a.m. and 7:59 a.m.', 'Between 8 a.m. and 8:59 a.m.',
       'Between 9 a.m. and 11:59 a.m.', 'Between 12 p.m. and 4:59 a.m.',
       'Children eligible for instruction in the minority official language',
       'Children not eligible for instruction in the minority official language'],
      dtype=object)

features_interest  = ['Total - Age groups of the population - 100% data',
                 'Total - Total income groups in 2020 for the population aged 15 years and over in private households - 100% data',
                 'Total - Occupied private dwellings by structural type of dwelling - 100% data',
                 'Total - Marital status for the total population aged 15 years and over - 100% data', Total - Secondary (high) school diploma or equivalency certificate for the population aged 15 years and over in private households - 25% sample data']

In [22]:
# List of values to filter the 'Lvl-0' column
filter_values = ['Total - Age groups of the population - 100% data',
                 'Total - Marital status for the total population aged 15 years and over - 100% data',
                 'Total - Total income groups in 2020 for the population aged 15 years and over in private households - 100% data',
                 'Total - Occupied private dwellings by structural type of dwelling - 100% data',
                 'Total - Marital status for the total population aged 15 years and over - 100% data',
                 'Total number of census families in private households - 100% data',
                'Total - Highest certificate, diploma or degree for the population aged 15 years and over in private households - 25% sample data',
                 'Total - Immigrant status and period of immigration for the population in private households - 25% sample data']

# Filtering the DataFrame based on the 'Lvl-0' column
features_df = df_census[df_census['Lvl-0'].isin(filter_values)]

# Display the first few rows of the filtered DataFrame
features_df.head()

features_df.to_csv('CensusdataOutput/filtered_data.csv')

### Separate Pivots for Features of Interest

In [23]:
age_group = df_census[df_census['Lvl-0'] == 'Total - Age groups of the population - 100% data']
pivot_age_group_sum = age_group.pivot_table(index='GEO_NAME', columns='Lvl-2', values='C1_COUNT_TOTAL', aggfunc = 'sum')
pivot_age_group_sum.to_csv('CensusdataOutput/pivot_age_group_CMA_level_sum.csv', sep =",")

In [24]:
total_dwellings = df_census[df_census['Lvl-0'] == 'Total - Occupied private dwellings by structural type of dwelling - 100% data']
pivot_total_dwellings_sum = total_dwellings.pivot_table(index='GEO_NAME', columns='Lvl-1', values='C1_COUNT_TOTAL', aggfunc = 'sum')
pivot_total_dwellings_sum.to_csv('CensusdataOutput/pivot_total_dwellings_sum.csv',sep =",")

In [25]:
education_level = df_census[df_census['Lvl-0']=='Total - Highest certificate, diploma or degree for the population aged 15 years and over in private households - 25% sample data']
pivot_education_sum = education_level.pivot_table(index = 'GEO_NAME', columns='Lvl-1', values='C1_COUNT_TOTAL', aggfunc = 'sum')
pivot_education_sum.to_csv('CensusdataOutput/pivot_education_sum.csv',sep =",")

In [26]:
total_income_groups = df_census[df_census['Lvl-0'] == 'Total - Total income groups in 2020 for the population aged 15 years and over in private households - 100% data']

pivot_total_income_groups_sum = total_income_groups.pivot_table(
    index='GEO_NAME',
    columns='Lvl-2',
    values='C1_COUNT_TOTAL',
    aggfunc='sum'
)
# Save the pivot table to CSV
pivot_total_income_groups_sum.to_csv('CensusdataOutput/pivot_total_income_groups_sum.csv', sep=",")

In [27]:
total_marital_status = df_census[df_census['Lvl-0'] == 'Total - Marital status for the total population aged 15 years and over - 100% data']
pivot_marital_status_sum = total_marital_status.pivot_table(index='GEO_NAME', columns='Lvl-1', values='C1_COUNT_TOTAL', aggfunc='sum')
pivot_marital_status_sum.to_csv('CensusdataOutput/pivot_marital_status_sum.csv', sep=",")

In [28]:
total_census_families = df_census[df_census['Lvl-0'] == 'Total number of census families in private households - 100% data']
pivot_total_census_families_sum = total_census_families.pivot_table(index='GEO_NAME', columns='Lvl-3', values='C1_COUNT_TOTAL', aggfunc = 'sum')
pivot_total_census_families_sum.to_csv('CensusdataOutput/pivot_total_census_families_sum.csv',sep =",")

In [29]:
Immigrant_status = df_census[df_census['Lvl-0'] == 'Total - Immigrant status and period of immigration for the population in private households - 25% sample data']
pivot_Immigrant_status_sum = Immigrant_status.pivot_table(index='GEO_NAME', columns='Lvl-1', values='C1_COUNT_TOTAL', aggfunc='sum')
pivot_Immigrant_status_sum.to_csv('CensusdataOutput/pivot_Immigrant_status_sum.csv', sep=",")

# Merging Data

In [30]:
import pandas as pd

# Assuming you have pivot_age_group_sum, pivot_education_sum, pivot_total_income_groups_sum,
# pivot_Immigrant_status_sum, pivot_marital_status_sum, pivot_total_census_families_sum,
# and pivot_total_dwellings_sum DataFrames defined

# Merge the DataFrames using pd.merge() and pass them as a list
combined_df = pd.merge(
    pivot_age_group_sum, pivot_education_sum,
    on="GEO_NAME", how="inner"
).merge(
    pivot_total_income_groups_sum, on="GEO_NAME", how="inner"
).merge(
    pivot_Immigrant_status_sum, on="GEO_NAME", how="inner"
).merge(
    pivot_marital_status_sum, on="GEO_NAME", how="inner"
).merge(
    pivot_total_census_families_sum, on="GEO_NAME", how="inner"
).merge(
    pivot_total_dwellings_sum, on="GEO_NAME", how="inner"
)

# Display the first few rows of the resulting DataFrame
combined_df.head()

C:\Users\panka\AppData\Local\Temp\ipykernel_24736\1819719565.py:8: FutureWarning: Passing 'suffixes' which cause duplicate columns {'0_x'} in the result is deprecated and will raise a MergeError in a future version.
  combined_df = pd.merge(
C:\Users\panka\AppData\Local\Temp\ipykernel_24736\1819719565.py:8: FutureWarning: Passing 'suffixes' which cause duplicate columns {'0_x'} in the result is deprecated and will raise a MergeError in a future version.
  combined_df = pd.merge(

,0_x,0 to 4 years,10 to 14 years,15 to 19 years,20 to 24 years,25 to 29 years,30 to 34 years,35 to 39 years,40 to 44 years,45 to 49 years,...,Without children,0,Apartment in a building that has fewer than five storeys,Apartment in a building that has five or more storeys,Apartment or flat in a duplex,Movable dwelling,Other single-attached house,Row house,Semi-detached house,Single-detached house
GEO_NAME,,,,,,,,,,,,,,,,,,,,,
Abbotsford - Mission,391450.0,10425.0,12225.0,11785.0,12395.0,12680.0,13690.0,14175.0,12885.0,12085.0,...,20920.0,67615.0,15550.0,1160.0,14035.0,335.0,60.0,5590.0,1710.0,29170.0
Alma,60660.0,1330.0,1775.0,1585.0,1390.0,1445.0,1510.0,1700.0,1910.0,1620.0,...,4505.0,13815.0,3225.0,30.0,1895.0,70.0,135.0,250.0,1070.0,7145.0
Amos,37755.0,955.0,1185.0,1045.0,990.0,1105.0,1110.0,1155.0,1255.0,1095.0,...,2520.0,8250.0,1830.0,5.0,600.0,70.0,45.0,185.0,275.0,5235.0
Baie-Comeau,53285.0,1085.0,1350.0,1235.0,1250.0,1255.0,1400.0,1455.0,1635.0,1595.0,...,4080.0,12360.0,2315.0,100.0,375.0,1280.0,65.0,295.0,750.0,7180.0
Barrie,425705.0,10830.0,13125.0,13070.0,13330.0,14160.0,14720.0,14455.0,13960.0,14110.0,...,22210.0,78540.0,6895.0,4430.0,4180.0,75.0,70.0,7020.0,2475.0,53395.0

In [33]:
combined_df.reset_index(inplace=True)
combined_df.columns

Index([                                                  'GEO_NAME',
                                                              '0_x',
                                                     '0 to 4 years',
                                                   '10 to 14 years',
                                                   '15 to 19 years',
                                                   '20 to 24 years',
                                                   '25 to 29 years',
                                                   '30 to 34 years',
                                                   '35 to 39 years',
                                                   '40 to 44 years',
                                                   '45 to 49 years',
                                                     '5 to 9 years',
                                                   '50 to 54 years',
                                                   '55 to 59 years',
                                                   '60 to 64 years',
                                                   '65 to 69 years',
                                                   '70 to 74 years',
                                                   '75 to 79 years',
                                                   '80 to 84 years',
                                                '85 years and over',
                                                              '0_y',
       'High (secondary) school diploma or equivalency certificate',
                                'No certificate, diploma or degree',
                     'Postsecondary certificate, diploma or degree',
                                                              '0_x',
                                               '$10,000 to $19,999',
                                                '$100,000 and over',
                                               '$20,000 to $29,999',
                                               '$30,000 to $39,999',
                                               '$40,000 to $49,999',
                                               '$50,000 to $59,999',
                                               '$60,000 to $69,999',
                                               '$70,000 to $79,999',
                                               '$80,000 to $89,999',
                                               '$90,000 to $99,999',
                                   'Under $10,000 (including loss)',
                                                              '0_y',
                                                       'Immigrants',
                                                   'Non-immigrants',
                                          'Non-permanent residents',
                                                              '0_x',
                                     'Married or living common-law',
                            'Not married and not living common-law',
                                                              '0_y',
                                                    'With children',
                                                 'Without children',
                                                                  0,
         'Apartment in a building that has fewer than five storeys',
            'Apartment in a building that has five or more storeys',
                                    'Apartment or flat in a duplex',
                                                 'Movable dwelling',
                                      'Other single-attached house',
                                                        'Row house',
                                              'Semi-detached house',
                                            'Single-detached house'],
      dtype='object')

In [34]:
columns_to_remove = ["0_x", "0_y",0]
final_cma_level_df = combined_df.drop(columns_to_remove,axis =1)
final_cma_level_df.to_csv("CensusdataOutput/final_cma_level_features.csv", index = False)